# Copyright 2018 Alfredo de la Fuente - AvanzOSC
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

{
    "name": "Jvv Group Custom",
    "summary": "Customization Module",
    "version": "16.0.1.0.0",
    "category": "Custom Module",
    "license": "AGPL-3",
    "author": "AvanzOSC",
    "website": "https://github.com/avanzosc/mrp-addons",
    "contributors": [
        "Ana Juaristi <anajuaristi@avanzosc.es>",
        "Alfredo de la Fuente <alfredodelafuente@avanzosc.es>",
    ],
    "depends": [
        "product_supplierinfo_for_customer",
        "mrp_subcontracting",
        "mrp_production_manual_close",
        "sale_order_line_dates",
        "mrp_sale_info",
        "mrp_production_sale_info",
        "confirmed_order_line_dates",
        "sale_order_line_qty_delivered",
        "stock_reserve",
        "product_code_builder",
        "warning",
        "mrp_sale_info",
        "account_voucher",
        "procurement_sale_forecast",
        "stock_move_extended_treeview",
        "sale_mrp_link",
        "sale_mrp_project_link",
        "mrp",
        "procurement_sale_forecast",
        "mrp_show_related_attachment",
        "sale_crm",
        "l10n_es_account_invoice_sequence",
        "hr",
        "project",
        "mrp_product_profit",
        "product_variant_supplierinfo",
        "hr_attendance_from_kanban",
        "mrp_chek_printed",
        "mrp_repair_partner_lot_product_variant",
        "sale_order_type",
        "mrp_production_qty_to_produce_info",
        "mrp_operations_extension",
        "stock_move_stencil_products",
        "stock_traceability_operation",
        "object_line_notes",
        "crm_claim_links",
        "hr_timesheet",
        "product_price_history",
        "mrp_production_estimated_cost",
        "sale_order_line_view",
        "product_expiry",
        "mrp_production_traceability",
        "stock_label_print",
        "project_task_code",
        "stock_transfer_split_multi_extend",
        "stock_quant_lot_ref",
        "stock_quant_reservation_status",
        "stock_available_unreserved",
        "stock_picking_package_info",
        "jvv_reports",
        "crm_claim_report",
        "crm_claim_corrective",
        "mrp_repair_partner_lot",
        "mrp_production_note",
        "warning_mrp",
        "mrp_production_estimated_cost",
        "stock_quant_valuation",
        "hr_attendance_from_kanban",
        "stock_available",
        "purchase",
        "mrp_operations_time_control",
        "jvv_project_ofid",
        "stock_information",
        "jvv_procurement_sale_forecast",
        "mrp_cancel_reserved",
        "procurement_purchase_forecast",
        "mrp_bom_cost_price",
        "product_last_mrp_info",
        "mrp_production_real_cost",
        "crm_claim_code",
        "stock_quant_expiry",
        "product_code",
        "hr_timesheet_invoice",
        "stock_lock_lot",
        "procurement_plan_mrp",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/jvv_custom_data.xml",
        "report/mrp_repair_report.xml",
        "report/stock_picking_report.xml",
        "report/mrp_production_report.xml",
        "report/quant_label_report.xml",
        "report/crm_claim_report.xml",
        "wizard/sale_line_forecast_load_view.xml",
        "wizard/wiz_change_serial_numbers_view.xml",
        "views/stock_move_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/product_supplierinfo_views.xml",
        "views/stock_location_views.xml",
        "views/stock_production_lot_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_picking_type_views.xml",
        "views/mrp_production_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_line_views.xml",
        "views/account_invoice_views.xml",
        "views/account_invoice_line_views.xml",
        "views/procurement_order_views.xml",
        "views/sale_order_views.xml",
        "views/mrp_production_workcenter_line_views.xml",
        "views/mrp_routing_views.xml",
        "views/mrp_routing_production_line_views.xml",
        "views/crm_lead_views.xml",
        "views/project_task_views.xml",
        "views/project_project_views.xml",
        "views/sale_report_views.xml",
        "views/purchase_report_views.xml",
        "views/project_template_views.xml",
        "views/report_stock_traceability_operation_views.xml",
        "views/purchase_order_line_views.xml",
        "views/stock_location_route_views.xml",
        "views/mrp_repair_views.xml",
        "views/mrp_repair_customer_lot_views.xml",
        "views/res_partner_views.xml",
        "views/mrp_routing_workcenter_views.xml",
        "views/project_task_type_views.xml",
        "views/crm_claim_views.xml",
        "views/stock_inventory_views.xml",
        "views/operation_time_line_views.xml",
        "views/procurement_sale_forecast_views.xml",
        "views/procurement_sale_forecast_line_views.xml",
        "views/procurement_sale_forecast_line2_views.xml",
        "views/mrp_bom_views.xml",
        "views/stock_quant_views.xml",
        "views/res_users_views.xml",
        "views/account_analytic_line_views.xml",
        "views/procurement_plan_views.xml",
        "wizard/wiz_change_product_category_view.xml",
        "wizard/wiz_create_procurement_forecast_line_view.xml",
        "wizard/update_bom_route_view.xml",
        "wizard/stock_transfer_details_view.xml",
        "wizard/assign_manual_quants_view.xml",
        "wizard/wiz_cancel_stock_picking_view.xml",
        "wizard/wiz_forecast_line2_to_sale_order_view.xml",
        "wizard/stock_transfer_split_multi_view.xml",
        "wizard/wiz_review_mrp_serial_view.xml",
    ],
    "installable": True,
}
